version: '3'

services:
  desktop:
    build: './src/desktop'
    volumes:
      - './src/desktop:/app'

  github-release:
    image: 'github-release'
    build: './src'

  www:
    image: 'tmvdl/projects:coins'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8080:80'
